server:
  port: 8080
spring:
  application:
    name: springbatch
  datasource:
    url: jdbc:mysql://localhost:3306/payroll?useSSL=false&allowPublicKeyRetrieval=true&maxReconnects=3&useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos
    username: root
    password: 12345678
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    root: INFO